### ISSUE TITLE
Icon does not show up in Utilities tab after running

### ISSUE THREAD

**Issue by poetro0** [cadifyai/Fusion-Exporter#1]
By following the setup instructions and then running the Add-In, the icon does not appear on the Utilities tab, but Fusion does say the program is running.

**Comment by siliconlad** [comment]
Can you show me the output of the text commands window @poetro0? You can access this by going to `File > View > Show Text Commands`

**Comment by poetro0** [comment]
**Here it is. I stopped and reran it ** 

===== Error =====
 run
Traceback (most recent call last):
  File "C:/Users/pietr/Downloads/Fusion-Exporter-0.1.0/FusionExporter.py", line 7, in run
    entry.start()
  File "C:\Users/pietr/Downloads/Fusion-Exporter-0.1.0\commands\entry.py", line 28, in start
    cmd_def = ui.commandDefinitions.addButtonDefinition(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pietr/AppData/Local/Autodesk/webdeploy/production/2f98b3925294fb88cbae05383e953941ed5106e7/Api/Python/packages\adsk\core.py", line 6330, in addButtonDefinition
    return _core.CommandDefinitions_addButtonDefinition(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 3 : invalid id

 ===== Error =====
 run
Traceback (most recent call last):
  File "C:/Users/pietr/Downloads/Fusion-Exporter-0.1.0/FusionExporter.py", line 7, in run
    entry.start()
  File "C:\Users/pietr/Downloads/Fusion-Exporter-0.1.0\commands\entry.py", line 28, in start
    cmd_def = ui.commandDefinitions.addButtonDefinition(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pietr/AppData/Local/Autodesk/webdeploy/production/2f98b3925294fb88cbae05383e953941ed5106e7/Api/Python/packages\adsk\core.py", line 6330, in addButtonDefinition
    return _core.CommandDefinitions_addButtonDefinition(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 3 : invalid id

**Comment by siliconlad** [comment]
Managed to reproduce the error. It should be fixed now in the latest release @poetro0. Thanks for bringing it to my attention!
